name: Test TYPO3 Extension

# Make sure only one build is running per branch at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: TYPO3 v12.4 tests on PHP ${{ matrix.php }}

    strategy:
      fail-fast: false
      matrix:
        php: [ 8.1, 8.2, 8.3 ]

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: 'xdebug3'
          extensions: pdo, sqlite3

      - name: 'Get Composer Cache Directory'
        id: composer-cache
        shell: bash
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: 'Cache Composer Dependencies'
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-php${{ matrix.php }}

      - name: 'Validate composer.json and composer.lock'
        shell: bash
        run: composer validate --strict

      - name: 'Install Composer Dependencies'
        shell: bash
        run: composer install --no-interaction

      - name: 'PHPUnit unit tests'
        shell: bash
        run: composer test-unit

      - name: 'PHPUnit functional tests'
        shell: bash
        run: composer test-functional

      - name: 'Merge Coverage Reports'
        shell: bash
        run: .Build/bin/phpcov merge --html .Build/artifacts/coverage/merged --clover .Build/artifacts/coverage/clover.xml .Build/artifacts/coverage/

      - name: 'Generate code coverage summary report'
        uses: saschanowak/CloverCodeCoverageSummary@0.4.0
        with:
          filename: .Build/artifacts/coverage/clover.xml

      - name: 'Add code coverage summary as action run comment'
        run: |
          cat code-coverage-summary.md >> $GITHUB_STEP_SUMMARY
          cat code-coverage-details.md >> $GITHUB_STEP_SUMMARY

      - name: 'Add title to code coverage summary'
        shell: bash
        run: sed -i '1 i\## TYPO3 v12.4 tests on PHP ${{ matrix.php }}' code-coverage-summary.md

      - name: 'Add code coverage summary as pr comment'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: coverage-${{ matrix.php }}
          recreate: true
          path: code-coverage-summary.md
